# -*- coding: utf-8 -*-
"""agentes_trabajo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ibMnLV4wzoR7HTRZTSoNGP9QUcqfF3lE
"""

1 #importar librerías
# AVANCE 1 - Importar librerías

# Librerías para manejo de datos
import pandas as pd
import numpy as np

# Librerías para gráficos
import matplotlib.pyplot as plt

# Librerías para dividir datos y validar modelos
from sklearn.model_selection import train_test_split, cross_val_score

# Librerías para normalizar datos
from sklearn.preprocessing import StandardScaler

# Librerías para imputar valores faltantes
from sklearn.impute import SimpleImputer

# Modelos de Machine Learning
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier

# Métricas de evaluación
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

# Librería para guardar el modelo entrenado
import joblib

2#cargar el dataset
# Cargar el dataset

# Cargar el archivo train.csv
df = pd.read_csv("train.csv")

# Mostrar las primeras filas del dataset
print("Primeras filas del dataset:")
display(df.head())

3# Revisar tamaño y columnas

# Mostrar cantidad de filas y columnas
print("Tamaño del dataset:", df.shape)

# Mostrar nombres de columnas
print("\nColumnas del dataset:")
print(df.columns.tolist())

4# Verificar datos faltantes

print("Valores nulos por columna:")
print(df.isnull().sum())

5# Información general del dataset

print("\nInformación general:")
df.info()

6# Estadísticas descriptivas

print("\nResumen estadístico:")
display(df.describe())

7# Verificar registros duplicados

duplicados = df.duplicated().sum()

print("Cantidad de registros duplicados:", duplicados)

8# AVANCE 2 - Agente 1 Normalizador

class AgenteNormalizador:
    """
    Agente encargado de limpiar, imputar, escalar y codificar el dataset.
    """

    def __init__(self, dataframe, columna_objetivo):
        # Copiamos el dataset original para no modificarlo directamente
        self.df = dataframe.copy()
        self.columna_objetivo = columna_objetivo

    def limpiar_datos(self):
        # Eliminar registros duplicados
        self.df = self.df.drop_duplicates()

        return self.df

    def separar_variables(self):
        # Separar variables predictoras y variable objetivo
        X = self.df.drop(self.columna_objetivo, axis=1)
        y = self.df[self.columna_objetivo]

        return X, y

    def insertar_nulos_artificiales(self, cantidad=20):
        # Insertar algunos nulos artificiales para demostrar la imputación
        columnas_numericas = self.df.select_dtypes(include=["int64", "float64"]).columns

        columnas_numericas = [
            columna for columna in columnas_numericas
            if columna != self.columna_objetivo
        ]

        for columna in columnas_numericas[:4]:
            indices = np.random.choice(self.df.index, size=cantidad, replace=False)
            self.df.loc[indices, columna] = np.nan

        return self.df

    def procesar(self):
        # Limpiar datos duplicados
        self.limpiar_datos()

        # Insertar valores nulos de prueba
        self.insertar_nulos_artificiales()

        # Separar variables
        X, y = self.separar_variables()

        # Codificar variables categóricas si existen
        X = pd.get_dummies(X, drop_first=True)

        # Imputar valores faltantes usando la media
        imputer = SimpleImputer(strategy="mean")
        X_imputado = imputer.fit_transform(X)

        # Escalar los datos para normalizarlos
        scaler = StandardScaler()
        X_escalado = scaler.fit_transform(X_imputado)

        # Convertir el resultado nuevamente a DataFrame
        X_limpio = pd.DataFrame(X_escalado, columns=X.columns)

        return X_limpio, y, imputer, scaler

9# Ejecutar Agente 1

# Crear el agente normalizador
agente1 = AgenteNormalizador(df, "price_range")

# Procesar el dataset
X_limpio, y, imputer, scaler = agente1.procesar()

# Mostrar las primeras filas del dataset limpio
display(X_limpio.head())

10# Guardar dataset limpio

# Unir variables limpias con la variable objetivo
dataset_limpio = X_limpio.copy()
dataset_limpio["price_range"] = y.values

# Guardar dataset limpio en CSV
dataset_limpio.to_csv("dataset_limpio.csv", index=False)

print("Dataset limpio guardado correctamente.")
print("Tamaño del dataset limpio:", dataset_limpio.shape)