# -*- coding: utf-8 -*-
"""agentes_trabajo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ibMnLV4wzoR7HTRZTSoNGP9QUcqfF3lE
"""

1 #importar librerías
# AVANCE 1 - Importar librerías

# Librerías para manejo de datos
import pandas as pd
import numpy as np

# Librerías para gráficos
import matplotlib.pyplot as plt

# Librerías para dividir datos y validar modelos
from sklearn.model_selection import train_test_split, cross_val_score

# Librerías para normalizar datos
from sklearn.preprocessing import StandardScaler

# Librerías para imputar valores faltantes
from sklearn.impute import SimpleImputer

# Modelos de Machine Learning
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier

# Métricas de evaluación
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

# Librería para guardar el modelo entrenado
import joblib

2#cargar el dataset
# Cargar el dataset

# Cargar el archivo train.csv
df = pd.read_csv("train.csv")

# Mostrar las primeras filas del dataset
print("Primeras filas del dataset:")
display(df.head())

3# Revisar tamaño y columnas

# Mostrar cantidad de filas y columnas
print("Tamaño del dataset:", df.shape)

# Mostrar nombres de columnas
print("\nColumnas del dataset:")
print(df.columns.tolist())

4# Verificar datos faltantes

print("Valores nulos por columna:")
print(df.isnull().sum())

5# Información general del dataset

print("\nInformación general:")
df.info()

6# Estadísticas descriptivas

print("\nResumen estadístico:")
display(df.describe())

7# Verificar registros duplicados

duplicados = df.duplicated().sum()

print("Cantidad de registros duplicados:", duplicados)