# -*- coding: utf-8 -*-
"""agentes_trabajo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ibMnLV4wzoR7HTRZTSoNGP9QUcqfF3lE
"""

1 #importar librerías
# AVANCE 1 - Importar librerías

# Librerías para manejo de datos
import pandas as pd
import numpy as np

# Librerías para gráficos
import matplotlib.pyplot as plt

# Librerías para dividir datos y validar modelos
from sklearn.model_selection import train_test_split, cross_val_score

# Librerías para normalizar datos
from sklearn.preprocessing import StandardScaler

# Librerías para imputar valores faltantes
from sklearn.impute import SimpleImputer

# Modelos de Machine Learning
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier

# Métricas de evaluación
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

# Librería para guardar el modelo entrenado
import joblib