# -*- coding: utf-8 -*-
"""agentes_trabajo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ibMnLV4wzoR7HTRZTSoNGP9QUcqfF3lE
"""

#importar librerías
# Librerías para manejo de datos
import pandas as pd
import numpy as np

# Librerías para gráficos
import matplotlib.pyplot as plt

# Librerías para dividir datos y validar modelos
from sklearn.model_selection import train_test_split, cross_val_score

# Librerías para normalizar datos
from sklearn.preprocessing import StandardScaler

# Librerías para imputar valores faltantes
from sklearn.impute import SimpleImputer

# Modelos de Machine Learning
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier

# Métricas de evaluación
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report

# Librería para guardar el modelo
import joblib

#cargar el dataset
# Cargar el archivo train.csv
df = pd.read_csv("train.csv")

# Mostrar las primeras filas del dataset
df.head()

# revisar tamaño y columnas
# Mostrar cantidad de filas y columnas
print("Tamaño del dataset:", df.shape)

# Mostrar nombres de columnas
print("Columnas del dataset:")
print(df.columns)

#verificar datos faltantes
# Revisar valores nulos por columna
print("Valores nulos por columna:")
print(df.isnull().sum())